function [name, data, comment] = convertXRengVar(name, data, mode)
%CONVERTXRENGVAR Processes data from a RBR engineering text file.
%
% This function is able to convert data retrieved from a RBR engineering
% text file generated by the Ruskin program.
%
% Inputs:
%   name        - RBR parameter name.
%   data        - data in RBR file.
%   mode        - Toolbox data type mode.
%
% Outputs:
%   name       - IMOS parameter code.
%   data       - data converted to fit IMOS parameter unit.
%   comment    - any comment on the parameter.
%
% Author:       Simon Spagnol <s.spagnol@aims.gov.au>
%

%
% Copyright (C) 2017, Australian Ocean Data Network (AODN) and Integrated
% Marine Observing System (IMOS).
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation version 3 of the License.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
% GNU General Public License for more details.

% You should have received a copy of the GNU General Public License
% along with this program.
% If not, see <https://www.gnu.org/licenses/gpl-3.0.en.html>.
%
narginchk(3, 3);

% name must always be set, data either passed through or modified, comment
% optional
comment = '';

switch name
    
    %Conductivity (mS/cm) = 10-1*(S/m)
    case 'Cond'
        name = 'CNDC';
        data = data/10;
        
        %Temperature (Celsius degree)
    case {'Temp', 'temp02', 'temp12'}
        name = 'TEMP';
        
        %Pressure (dBar)
    case {'Pres', 'pres20', 'pres21', 'pres26'}
        name = 'PRES';
        
        %Relative Pressure (dBar)
    case {'pres08'}
        name = 'PRES_REL';
        
        %Fluorometry-chlorophyl (ug/l) = (mg.m-3)
    case {'FlC', 'FlCa'}
        name = 'CPHL';
        comment = ['Artificial chlorophyll data computed from ' ...
            'fluorometry sensor raw counts measurements. Originally ' ...
            'expressed in ug/l, 1l = 0.001m3 was assumed.'];
        
        %Turbidity (NTU)
    case {'Turb', 'Turba'}
        name = 'TURB';
        
        %Rinko temperature (Celsius degree)
    case 'R_Temp'
        name = '';
        comment = 'Corrected temperature.';
        
        %Rinko dissolved O2 (%)
    case 'R_D_O2'
        name = 'DOXS';
        
        %Depth (m)
    case {'Depth', 'dpth01'}
        name = 'DEPTH';
        
        %Salinity (PSU)
    case 'Salin'
        name = 'PSAL';
        
        %Specific conductivity (uS/cm) = 10-4 * (S/m)
    case 'SpecCond'
        name = 'SPEC_CNDC';
        data = data/10000;
        
        %Density anomaly (n/a)
    case 'DensAnom'
        name = '';
        
        %Speed of sound (m/s)
    case 'SoSUN'
        name = 'SSPD';
        
        %Rinko dissolved O2 concentration (mg/l)
    case 'rdO2C'
        name = 'DOXY';
        
        % Oxyguard dissolved O2 (%)
    case 'D_O2'
        name = 'DOXS';
        
        % Oxyguard dissolved O2 concentration (ml/l)
    case 'dO2C'
        name = 'DOX';
        
        % not IMOS
    otherwise
        name = ''; 
end

end