function sample_data = echoview_extendedParse( filename, platform )
%ECHOVIEW_EXTENDEDPARSE Parses EchoView results CSV file with extra variables.
%
% This is an early draft attempt to parse an echoview results
% comma separated variable (CSV) file into a sample_data struct.
%
% This function is almost a generic CSV Parser.
% The list of fields to define and the column names that populate those
% fields are defined in a text file './Parser/echoview_config.txt' or the
% file specified by the property 'echoview.config' if defined.
%
% Limitations:
%   Text quoting is not properly supported (fields cannot contain ,)
%   Dates are only supported in the format yyyymmdd
%   Times are only supported in the format HH:MM:SS.ss
%   Timestamps are only supported as a date field followed by a time field
%   yyyymmdd, HH:MM:SS.ss
%
% Inputs:
%   filename    - CSV results file generated by echoview.
%   platform    - Platform code  
% 
% Outputs:
%   sample_data - Struct containing sample data.
%
% Externals:
%   Property 'echoview.config' and the file it specifies or
%   the file './Parser/echoview_config.txt'
%
% Author: Gordon Keith <gordon.keith@csiro.au>
% 

% Copyright (c) 2010, CSIRO.
% This source is based on and uses code fragments from code that is:
%
% Copyright (c) 2009, eMarine Information Infrastructure (eMII) and Integrated 
% Marine Observing System (IMOS).
% All rights reserved.
% 
% Redistribution and use in source and binary forms, with or without 
% modification, are permitted provided that the following conditions are met:
% 
%     * Redistributions of source code must retain the above copyright notice, 
%       this list of conditions and the following disclaimer.
%     * Redistributions in binary form must reproduce the above copyright 
%       notice, this list of conditions and the following disclaimer in the 
%       documentation and/or other materials provided with the distribution.
%     * Neither the name of the eMII/IMOS nor the names of its contributors 
%       may be used to endorse or promote products derived from this software 
%       without specific prior written permission.
% 
% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
% AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
% IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
% ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE 
% LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
% CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
% SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
% INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
% CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
% ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
% POSSIBILITY OF SUCH DAMAGE.
%

  error(nargchk(1,2,nargin));
  
  if nargin < 2, platform = '' ; end
  
  sample_data = echoviewParse(filename, platform, 'echoview_extend.txt');
  
end
